name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check if the repository is private
        if: ${{ github.event.repository.private }}
        run: exit 1
        
      - name: Tests
        uses: Ivanusdx/test-project-action@v1
        with:
          project: 'ono-tebe-nado_project'
